### DISCUSSION TITLE
Fullwidth dashboard

### DISCUSSION THREAD

**Discussion by bbohling** [TfTHacker/DashboardPlusPlus#13] [General]
So the only way I could get fullwidth to work was to modify **dashboard-ReadLineLength.css** to also include:

```css
.contextual-typography .markdown-preview-view.is-readable-line-width .markdown-preview-sizer>div {
   width: 100%;
}
```

I realize this isn't a solution that would work for everyone since they may not have the contextual-typography plugin. But I did want to bring it up in case you had thoughts or others have run into the same issue.

I did just update all my plugins and theme (minimal) but it certainly could still be something conflicting.
