### DISCUSSION TITLE
Use dataviewjs to fill lists

### DISCUSSION THREAD

**Discussion by soloam** [TfTHacker/DashboardPlusPlus#34] [Q&A]
Hello I tried to make a dataviewjs to fill the lists of the dashboard:

```
dv.paragraph("<ul><li>Sub 1<ul><li>Sub 10</li><li>Sub 11</li></ul></li></ul>");
```

In the end I render the list but no css is applied to format the lists! Is this possible? I was trying to make my dashboard a little more dynamic!

Thank you

**Comment by soloam** [comment]
I solved this issue with by adding a new css file to snipettes with:

```css
.dashboard div.markdown-preview-section > div.el-pre > div.block-language-dataviewjs > p > span > ul {
  list-style: none;
  display: flex;
  column-gap: 50px;
  flex-flow: row wrap;
}

.dashboard div.block-language-dataviewjs > p > span > ul > li {
  min-width: 250px;
  width: 15%;
  list-style-type: none;
}

.dashboard div.block-language-dataviewjs > p > span > ul > li ::marker {
  font-size: 0.8em;
}
```

Probably it could be better, but for me it's working
